# Generated by Django 2.1.1 on 2018-09-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fx',
            fields=[
                ('currency_cn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('currency_en', models.CharField(max_length=20)),
                ('cash_buying', models.CharField(max_length=20)),
                ('cash_selling', models.CharField(max_length=20)),
                ('spot_buying', models.CharField(max_length=20)),
                ('spot_selling', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'testdb',
                'managed': True,
            },
        ),
    ]
