# Generated by Django 2.1.1 on 2018-09-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fx',
            options={},
        ),
        migrations.AlterModelTable(
            name='fx',
            table=None,
        ),
    ]
